### ISSUE TITLE
мама приезжай ты меня забери

### ISSUE THREAD

**Issue by Lumiwarum** [YeslieSnayder/OperatingSystems#1]
не живым

**Comment by YeslieSnayder** [comment]
так хоть мёртвым, но меня забери.

**Comment by Lumiwarum** [comment]
ты блять

**Comment by YeslieSnayder** [comment]
ладно

**Comment by Lumiwarum** [comment]
нахуя закрыл

**Comment by YeslieSnayder** [comment]
ты БЛЯТЬ!

**Comment by YeslieSnayder** [comment]
УЭУУУУЭУЭУЭУЭЭЭЭЭЭЭЭЭЭЭЭЭ

**Comment by YeslieSnayder** [comment]
я тебя щас уебу УУУУУУУУУУЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭ

**Comment by Lumiwarum** [comment]
ыыыыыыы

**Comment by YeslieSnayder** [comment]
ты какую группу уважаешь?

**Comment by Lumiwarum** [comment]
пугачеву

**Comment by YeslieSnayder** [comment]
ТЫ ЧЕ АХУЕЛ ЧТОЛИ?! Я НЕНАВИЖУ АЛЛУ ПУГАЧЕВУ!

**Comment by YeslieSnayder** [comment]
УУУУУУУУУУУУАААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААААА!

**Comment by Lumiwarum** [comment]
ууауауауауауауауа

**Comment by YeslieSnayder** [comment]
я уважаю группу дип пёрпл.
